### PR TITLE
Port to DBus Sharp

### PR DESCRIPTION
**Pull request by alucryd**
Upon packaging 3.4.1 for Arch Linux, I noticed that ndesk-dbus and ndesk-dbus-glib were gone from our repos. It appears they have been forked and are now called dbus-sharp [1] and dbus-sharp-glib [2], they are already used in Banshee and Tomboy in place of the older NDesk.

Those changes allow the mono interface to be built against them, hope I did it right.

[1] https://github.com/mono/dbus-sharp
[2] https://github.com/mono/dbus-sharp-glib

### CODE REVIEW

**Comment by matttbe** [comment]
Hello Maxime,

Thank you for this bug report and this patch! :-)
Do you have any idea if it's a "new" project? I can find packages in  previous Debian/Ubuntu versions. I guess/hope we don't have to support both versions :-)

And did you try the demo (demo-mono) to check if everything is working well? :-)

**Comment by alucryd** [comment]
As far as I can tell, it is newer than ndesk's implementation and is meant to replace it, also I guess being on Mono's GitHub would make it the "official" DBus Mono implementation. Debian/Ubuntu are probably just lagging behind.

I have trouble running the demo-mono, as well as the demo-vala (the python, ruby and bash seem to work fine).  I'm getting this in a terminal:
  sh: ./demo_mono: No such file or directory
  sh: ./demo_vala: No such file or directory

Any idea what could cause this?

**Comment by alucryd** [comment]
Okay figured it out, obviously I had to compile the source code for the demo. It is working fine after compilation.

**Comment by matttbe** [comment]
> As far as I can tell, it is newer than ndesk's implementation and is meant to replace it, also I guess being on Mono's GitHub would make it the "official" DBus Mono implementation. Debian/Ubuntu are probably just lagging behind.

Yes it seems these packages are already available in Debian, Ubuntu, Fedora, etc. from a few time now.
Then we can remove the support of DBus' NDesk.

> Okay figured it out, obviously I had to compile the source code for the demo. It is working fine after compilation.

Nice, thank you :-)

> Edit: I'll also look into using gtk-sharp3 instead of 2 later since I believe you dropped gtk2 support a while ago.

Good idea! :-)

**Pull request merged**
